#!/bin/bash
# Reference: https://github.com/Velocidex/velociraptor and https://github.com/weslambert/velocistack

# Exit immediately if a command exits with a non-zero status
set -e

source "./libs/main.sh"
define_env
define_paths
source "./libs/install-helper.sh"

# Define necessary variables
src_dir="/path/to/source"
service_name="velociraptor"
workdir="/path/to/workdir"
VELOX_USER=$(get_env_value 'VELOX_USER')

# Step 1: Pre-installation
pre_install "velociraptor" false

# Step 2: Prepare environment settings
rsync -a "${src_dir}/docker-compose.yaml" .
rsync -a "${src_dir}/entrypoint" .
rsync -a "${src_dir}/Dockerfile" .
rsync -a "${src_dir}/.env" .

# Grab variables from the default.env file and add them to the .env file to use in the docker-compose
for var in VELOX_PASSWORD VELOX_ROLE VELOX_USER VELOX_FRONTEND_HOSTNAME VELOX_SERVER_URL VELOX_PASSWORD_2 VELOX_ROLE_2 VELOX_USER_2; do
  replace_env "$var"
done

docker compose up -d --build
print_yellow "Waiting for the $service_name service to start..."
sleep 5
docker compose stop

# Step 3: Update permissions and add custom resources
sudo chmod 755 -R "${workdir}/${service_name}/velociraptor"
sudo rsync -a "${src_dir}/custom" .
print_yellow "Adding custom resources and restarting the $service_name service..."

# Step 3.1: Add custom artifacts
cd "${workdir}/${service_name}"
if [[ -v VELOCIRAPTOR_ARTIFACTS_URL ]]; then
  download_external_file "$VELOCIRAPTOR_ARTIFACTS_URL" velociraptor_artifacts.zip
  unzip -q -o velociraptor_artifacts.zip -d server_artifacts
  sudo chown -R root:root server_artifacts/*
  sudo rsync -r server_artifacts/* "$VELOCIRAPTOR_ARTIFACTS_DST_FOLDER"
  sudo rm -rf server_artifacts velociraptor_artifacts.zip
fi

if [ -d custom ]; then
  echo "Using custom artifacts"
  sudo mv custom/* "$VELOCIRAPTOR_ARTIFACTS_DST_FOLDER"
  sudo rm -rf custom
  sudo chown -R root:root "$VELOCIRAPTOR_ARTIFACTS_DST_FOLDER"
else
  echo "Artifacts not found, using entrypoint artifacts"
fi

# Step 4: Finally restart the service
docker compose restart
print_green_v2 "$service_name deployment started." "Successfully"

# Step 5: Show login credentials
_VELOX_USER=$(get_env_value 'VELOX_USER')
_VELOX_PASSWORD=$(get_env_value 'VELOX_PASSWORD')
print_with_border "$service_name credentials:"
echo "Username: $_VELOX_USER"
echo "Password: $_VELOX_PASSWORD"

# If the VELOX_USER is not defined in the global .env, then add creds to the .env file
if [[ -z $VELOX_USER ]]; then
  msg1="### Generated by $service_name scripts ###"
  msg2="### $service_name end ###"
  # Remove the existing credentials
  sed -i "/$msg1/,/$msg2/d" "${workdir}/.env"
  print_green "$service_name credentials added to the .env file"

  {
    echo "$msg1"
    echo "VELOCIRAPTOR_USERNAME=$_VELOX_USER"
    echo "VELOCIRAPTOR_PASSWORD=$_VELOX_PASSWORD"
    echo "$msg2"
  } >>"${workdir}/.env"
fi
