#Reference https://github.com/Velocidex/velociraptor and https://github.com/weslambert/velocistack
home_path=$1
git clone https://github.com/weslambert/velociraptor-docker
cd velociraptor-docker
cp $home_path/resources/velociraptor/docker-compose.yaml .
cp $home_path/resources/velociraptor/entrypoint .

export VELOX_USER=${VELOCIRAPTOR_USERNAME:-$VELOX_USER}
export VELOX_PASSWORD=${VELOCIRAPTOR_PASSWORD:-$VELOX_PASSWORD}

echo "VELOX_USER=$VELOX_USER"
echo "VELOX_PASSWORD=$VELOX_PASSWORD"

sudo docker compose build
sudo docker compose up -d
echo "Sleeping for 5 seconds to let the services start..."
sleep 5

sudo chmod 777 -R $home_path/scripts/velociraptor-docker/velociraptor
sudo chmod 777 -R $home_path/scripts/velociraptor-docker/velociraptor/clients
cd velociraptor
cp -R $home_path/resources/velociraptor/custom/ .
sudo docker restart velociraptor

# Show login credentials
echo "############################################"
echo "Velociraptor credentials:"
echo "Username: $VELOX_USER"
echo "Password: $VELOX_PASSWORD"
echo "############################################"
# Bash check if the  VELOCIRAPTOR_USERNAME and VELOCIRAPTOR_PASSWORD env exist in the .env file
if grep -q "VELOCIRAPTOR_USERNAME" "$home_path/scripts/.env"; then
    echo "Velociraptor credentials already exist in the .env file"
else
    echo "Velociraptor credentials added to the .env file"
    echo "### Autogenerated by Velociraptor ###" >> "$home_path/scripts/.env"
    echo "VELOCIRAPTOR_USERNAME=$VELOX_USER" >> "$home_path/scripts/.env"
    echo "VELOCIRAPTOR_PASSWORD=$VELOX_PASSWORD" >> "$home_path/scripts/.env"
fi
